version: '2'

services:
  elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch-1
    mem_limit: 2g
    volumes:
      - "./data-1:/usr/share/elasticsearch/data"
      - "./elasticsearch-1.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./certificates/ca/ca.crt:/usr/share/elasticsearch/config/x-pack/tls/ca/ca.crt"
      - "./certificates/node-0001:/usr/share/elasticsearch/config/x-pack/tls/node-0001"
    networks:
      internal-tls:
        ipv4_address: 172.18.10.2
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  elasticsearch-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch-2
    mem_limit: 2g
    volumes:
      - "./data-2:/usr/share/elasticsearch/data"
      - "./elasticsearch-2.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./certificates/ca/ca.crt:/usr/share/elasticsearch/config/x-pack/tls/ca/ca.crt"
      - "./certificates/node-0002:/usr/share/elasticsearch/config/x-pack/tls/node-0002"
    networks:
      internal-tls:
        ipv4_address: 172.18.10.3
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  # This is an alien with a cert from a different CA
  elasticsearch-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch-3
    mem_limit: 2g
    volumes:
      - "./data-3:/usr/share/elasticsearch/data"
      - "./elasticsearch-3.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./alien-certificates/ca/ca.crt:/usr/share/elasticsearch/config/x-pack/tls/ca/ca.crt"
      - "./alien-certificates/node-0003:/usr/share/elasticsearch/config/x-pack/tls/node-0003"
    networks:
      internal-tls:
        ipv4_address: 172.18.10.4
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

networks:
  internal-tls:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.10.0/24
        gateway: 172.18.10.1
